name: hydro_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Gestión de estado
  provider: ^6.1.1
  
  # Conectividad IoT
  mqtt_client: ^10.2.0
  http: ^1.2.0
  
  # Base de datos local (para producción)
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
